### ISSUE TITLE
Awesome Thinsboard collection

### ISSUE THREAD

**Issue by devaskim** [a631953720/thingsboard-tools2.0#14]
Hi
I want to create a collection of [awesome Thingsboard things](https://github.com/devaskim/awesome-thingsboard). Could you please provide me very basic description about what this repo is for? I try to translate with Google but I afraid that I don't understand the main idea.
Thanks in advance

**Comment by a631953720** [comment]
Hi @devaskim ,

I will try to write an English readme to describe this repo.
My English is poor, but I will try my best :D

**Comment by a631953720** [comment]
After PR #15  and some new commits, this repo has English docs now. 
Hope that can help you.

**Comment by devaskim** [comment]
Awesome! And thanks!
I added your project to the [Tools](https://github.com/devaskim/awesome-thingsboard/blob/main/README.md#tools) section
